// Package chiefver records which upstream chief revision is vendored here.
//
// Generated by scripts/sync-upstream.sh. Do not edit.
package chiefver

const (
	// Ref is the upstream git tag or describe output, e.g. "v0.8.0".
	Ref = "v0.8.0"
	// Commit is the full upstream commit SHA.
	Commit = "18fce693067e8b8ee36010c1d3b267e00d4025f7"
)
