#!/usr/bin/env bash
#
# Regenerate internal/chief/ from the pinned third_party/chief submodule.
#
#   scripts/sync-upstream.sh [<tag>] [--check]
#
# With --check the tree is regenerated into a temporary directory and diffed
# against internal/chief/ instead of overwriting it. That is the CI gate: any
# hand-edit to a vendored file fails the build. Files matching *_ext.go are our
# own additions to the vendored packages and are excluded from the comparison.
#
# The vendored packages live in the SAME Go package as upstream, so our _ext.go
# files can reach unexported identifiers. That is what lets us extend chief
# without patching it. patches/ exists as insurance and is empty by default.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUBMODULE="$REPO_ROOT/third_party/chief"
DEST="$REPO_ROOT/internal/chief"
MANIFEST_NAME="UPSTREAM.manifest"

MODULE_PATH="github.com/dripcoder/loop"
UPSTREAM_MODULE="github.com/minicodemonkey/chief"

# Packages copied out of upstream's internal/ tree. `tui` is deliberately absent
# — its policy is reimplemented in internal/session. `cmd` and `update` are
# absent because they are CLI entry points we do not reuse.
PACKAGES=(loop agent prd git config)

TAG=""
CHECK=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    -*)      echo "unknown flag: $arg" >&2; exit 2 ;;
    *)       TAG="$arg" ;;
  esac
done

die() { echo "sync-upstream: $*" >&2; exit 1; }

[[ -d "$SUBMODULE/.git" || -f "$SUBMODULE/.git" ]] \
  || die "submodule missing — run: git submodule update --init --recursive"

# ---------------------------------------------------------------- checkout ---
if [[ -n "$TAG" ]]; then
  echo "==> fetching upstream $TAG"
  git -C "$SUBMODULE" fetch --tags --quiet origin
  git -C "$SUBMODULE" checkout --quiet "$TAG"
fi

UPSTREAM_REF="$(git -C "$SUBMODULE" describe --tags --always --dirty)"
UPSTREAM_SHA="$(git -C "$SUBMODULE" rev-parse HEAD)"
echo "==> upstream $UPSTREAM_REF ($UPSTREAM_SHA)"

git -C "$SUBMODULE" diff --quiet HEAD -- \
  || die "submodule working tree is dirty; commit or discard there first"

# ------------------------------------------------------------- staging dir ---
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

for pkg in "${PACKAGES[@]}"; do
  src="$SUBMODULE/internal/$pkg"
  [[ -d "$src" ]] || die "upstream package not found: internal/$pkg"
  mkdir -p "$STAGE/$pkg"
  # Test files and testdata come along deliberately: running upstream's own
  # suite against the rewritten tree is our regression check on both the
  # rewrite and upstream drift.
  find "$src" -mindepth 1 -maxdepth 1 -name '*.go' -exec cp {} "$STAGE/$pkg/" \;
  [[ -d "$src/testdata" ]] && cp -R "$src/testdata" "$STAGE/$pkg/testdata"
done

# --------------------------------------------------------- import rewriting ---
# Only the internal/ tree moves. `github.com/minicodemonkey/chief/embed` is a
# public package and stays a real go.mod dependency, so it must NOT be rewritten
# — the trailing "/internal/" in the pattern is what keeps it intact.
echo "==> rewriting imports"
find "$STAGE" -name '*.go' -print0 | while IFS= read -r -d '' f; do
  perl -0pi -e "s{\Q$UPSTREAM_MODULE/internal/\E}{$MODULE_PATH/internal/chief/}g" "$f"
done

if grep -rn "$UPSTREAM_MODULE/internal/" "$STAGE" >/dev/null 2>&1; then
  die "import rewriting missed occurrences (see grep above)"
fi

cp "$SUBMODULE/LICENSE" "$STAGE/LICENSE"

# ------------------------------------------------------------ manifest ------
# Recorded per file so `--check` can detect deletions as well as edits, and so a
# reviewer can see at a glance which upstream revision a file came from.
{
  echo "# Generated by scripts/sync-upstream.sh — do not edit."
  echo "# upstream: $UPSTREAM_MODULE"
  echo "# ref:      $UPSTREAM_REF"
  echo "# commit:   $UPSTREAM_SHA"
  echo "#"
  echo "# sha256  path"
  (cd "$STAGE" && find . -type f ! -name "$MANIFEST_NAME" | sed 's|^\./||' | LC_ALL=C sort \
    | while IFS= read -r rel; do
        printf '%s  %s\n' "$(shasum -a 256 "$rel" | cut -d' ' -f1)" "$rel"
      done)
} > "$STAGE/$MANIFEST_NAME"

cat > "$STAGE/UPSTREAM.md" <<EOF
# Vendored from chief

**Do not hand-edit anything in this directory.** It is regenerated by
\`scripts/sync-upstream.sh\` and \`task verify-vendor\` fails the build on any
manual change.

| | |
|---|---|
| Upstream | <https://github.com/MiniCodeMonkey/chief> |
| Ref | \`$UPSTREAM_REF\` |
| Commit | \`$UPSTREAM_SHA\` |
| License | MIT — see [LICENSE](LICENSE) and the repository [NOTICE](../../NOTICE) |

Import paths are rewritten from \`$UPSTREAM_MODULE/internal/...\` to
\`$MODULE_PATH/internal/chief/...\`. The public \`$UPSTREAM_MODULE/embed\`
package is *not* vendored — it is a normal module dependency.

## Extending vendored packages

Files named \`*_ext.go\` are ours. They live in the same Go package as the
vendored source, so they can use unexported identifiers, and the sync script
never deletes them. Prefer an \`_ext.go\` file over a patch; \`patches/\` should
stay empty.

To update: \`task sync-upstream -- v0.9.0\`
EOF

# ---------------------------------------------------------------- compare ----
# _ext.go files are ours and have no upstream counterpart, so they are excluded
# from both the wipe and the comparison.
EXCLUDES=(-x '*_ext.go' -x '*_ext_test.go')

if [[ "$CHECK" == "1" ]]; then
  echo "==> verifying internal/chief/ matches a fresh sync"
  [[ -d "$DEST" ]] || die "internal/chief/ does not exist — run sync-upstream first"
  if diff -r "${EXCLUDES[@]}" "$STAGE" "$DEST"; then
    echo "==> vendored tree is clean"
    exit 0
  fi
  die "internal/chief/ has drifted from upstream.
     Either revert the hand-edit, or move the change into a *_ext.go file
     (same package, so unexported identifiers are reachable), or add a patch
     under patches/ if it genuinely must modify upstream source."
fi

# ------------------------------------------------------------------ write ----
echo "==> writing internal/chief/"
mkdir -p "$DEST"
# Remove everything except our _ext.go additions, so upstream deletions
# propagate rather than lingering as orphans.
find "$DEST" -mindepth 1 ! -name '*_ext.go' ! -name '*_ext_test.go' -delete 2>/dev/null || true
cp -R "$STAGE/." "$DEST/"

mkdir -p "$REPO_ROOT/THIRD_PARTY_LICENSES"
cp "$SUBMODULE/LICENSE" "$REPO_ROOT/THIRD_PARTY_LICENSES/chief-LICENSE"

# ---------------------------------------------------------------- patches ----
shopt -s nullglob
patches=("$REPO_ROOT"/patches/*.patch)
shopt -u nullglob
if (( ${#patches[@]} )); then
  echo "==> applying ${#patches[@]} patch(es)"
  for p in "${patches[@]}"; do
    echo "    $(basename "$p")"
    git -C "$REPO_ROOT" apply --3way "$p" \
      || die "patch failed: $(basename "$p") — rebase it against $UPSTREAM_REF"
  done
fi

# ----------------------------------------------------------------- verify ----
echo "==> building"
(cd "$REPO_ROOT" && go build ./... )
echo "==> running upstream test suite"
(cd "$REPO_ROOT" && go test ./internal/chief/... )

echo "==> synced to $UPSTREAM_REF"
